apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

components:
- ../../middleware/mysql
- ../../middleware/redis

patches:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: bgd
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: yellow
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: mysql
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: mysql:5.7.43
