apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-specific-ip
spec:
  podSelector:
    matchLabels:
      app: mysql
  ingress:
  - from:
    - ipBlock:
        cidr: 10.0.182.220/32 
  ports:
  - protocol: TCP
    port: 3306
