apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: bgd
    patch: |-
      - op: add #action
        path: "/spec/template/spec/nodeSelector" 
        value:           
          mynode: test
